# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: turtlpass.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'turtlpass.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fturtlpass.proto\x12\tturtlpass\"^\n\x16GeneratePasswordParams\x12\x0f\n\x07\x65ntropy\x18\x01 \x01(\x0c\x12\x0e\n\x06length\x18\x02 \x01(\r\x12#\n\x07\x63harset\x18\x03 \x01(\x0e\x32\x12.turtlpass.Charset\"$\n\x14InitializeSeedParams\x12\x0c\n\x04seed\x18\x01 \x01(\x0c\"\x9f\x01\n\nDeviceInfo\x12\x19\n\x11turtlpass_version\x18\x01 \x01(\t\x12\x17\n\x0f\x61rduino_version\x18\x02 \x01(\t\x12\x18\n\x10\x63ompiler_version\x18\x03 \x01(\t\x12\x16\n\x0enanopb_version\x18\x04 \x01(\t\x12\x12\n\nboard_name\x18\x05 \x01(\t\x12\x17\n\x0funique_board_id\x18\x06 \x01(\x0c\"\xaa\x01\n\x07\x43ommand\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.turtlpass.CommandType\x12\x35\n\x08gen_pass\x18\x02 \x01(\x0b\x32!.turtlpass.GeneratePasswordParamsH\x00\x12\x34\n\tinit_seed\x18\x03 \x01(\x0b\x32\x1f.turtlpass.InitializeSeedParamsH\x00\x42\x0c\n\nparameters\"z\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12#\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x14.turtlpass.ErrorCode\x12*\n\x0b\x64\x65vice_info\x18\x03 \x01(\x0b\x32\x15.turtlpass.DeviceInfo\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c*n\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0fGET_DEVICE_INFO\x10\x01\x12\x13\n\x0fINITIALIZE_SEED\x10\x02\x12\x15\n\x11GENERATE_PASSWORD\x10\x03\x12\x11\n\rFACTORY_RESET\x10\x04*_\n\x07\x43harset\x12\x10\n\x0cLETTERS_ONLY\x10\x00\x12\x10\n\x0cNUMBERS_ONLY\x10\x01\x12\x13\n\x0fLETTERS_NUMBERS\x10\x02\x12\x1b\n\x17LETTERS_NUMBERS_SYMBOLS\x10\x03*\x89\x02\n\tErrorCode\x12\x08\n\x04NONE\x10\x00\x12\x13\n\x0fINVALID_COMMAND\x10\x01\x12\x12\n\x0eINVALID_PARAMS\x10\x02\x12\x1a\n\x16INVALID_ENTROPY_LENGTH\x10\x03\x12\x1b\n\x17INVALID_PASSWORD_LENGTH\x10\x04\x12\x17\n\x13INVALID_SEED_LENGTH\x10\x05\x12\x18\n\x14SEED_NOT_INITIALIZED\x10\x06\x12\x13\n\x0fPASSWORD_FAILED\x10\x07\x12\x19\n\x15PROTO_DECODING_FAILED\x10\x08\x12\x19\n\x15PROTO_ENCODING_FAILED\x10\t\x12\x12\n\x0eINTERNAL_ERROR\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turtlpass_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=623
  _globals['_COMMANDTYPE']._serialized_end=733
  _globals['_CHARSET']._serialized_start=735
  _globals['_CHARSET']._serialized_end=830
  _globals['_ERRORCODE']._serialized_start=833
  _globals['_ERRORCODE']._serialized_end=1098
  _globals['_GENERATEPASSWORDPARAMS']._serialized_start=30
  _globals['_GENERATEPASSWORDPARAMS']._serialized_end=124
  _globals['_INITIALIZESEEDPARAMS']._serialized_start=126
  _globals['_INITIALIZESEEDPARAMS']._serialized_end=162
  _globals['_DEVICEINFO']._serialized_start=165
  _globals['_DEVICEINFO']._serialized_end=324
  _globals['_COMMAND']._serialized_start=327
  _globals['_COMMAND']._serialized_end=497
  _globals['_RESPONSE']._serialized_start=499
  _globals['_RESPONSE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
